### PR TITLE
fix subitem selection detection on android

### PR DESCRIPTION
**Pull request by danielang**
submit menuIndex in JS-callback.
This will fix issue #6

### CODE REVIEW

**Comment by prscX** [comment]
Thanks @danielang for the PR.

I have merged the same, coming weekend I am planning to release it with few other fix's as well.

Thanks 
Pranav

**Comment by danielang** [comment]
Hey @prscX 
What other fixes do you have planned?
Is there a fix for displaying images in a menuitem? I dont get it to work on both Android and iOS. I do a simple `require('to/image/source')` but the code fails on native side.
Thank you!

**Comment by prscX** [comment]
Hi @danielang, Yes the icons issue is fixed now, hope now you will be able to show icons and get proper callbacks as well.

Please let me know in case it does not works.

[v0.0.3](https://github.com/prscX/react-native-popover-menu/releases/tag/v0.0.3)

Thanks
Pranav

**Comment by danielang** [comment]
Hey @prscX,
very nice it works well 🙂 but I've a problem on Android: The icon color is really dark. Is this an effect which was added by android-popover-library?

The screen:  
screenshot_1519067680 

The original pictures:  
en
de


Thank you

**Comment by prscX** [comment]
That's strange @danielang, I don't think native library is doing anything special on icons, today I will test using same icons and will share the results.

Thanks
Pranav

**Comment by prscX** [comment]
Hi @danielang, I have found the root cause, basically the native library was setting tint color for images. 

I have set `imageTintMode` to `PorterDuff.Mode.DST`, but this API is available only for android SDK 21 and above. I have added `@TargetApi(21)` annotation to native method. Hope it should work for you.

Can you please download the latest V0.0.4 and test the same. Please let me know in case it does not works.

Thanks
Pranav

**Comment by danielang** [comment]
Hey @prscX 
this works for me! thank you 👍 

Daniel

**Pull request merged**
