### PR TITLE
Adds shadow support

### PR DESCRIPTION
**Pull request by flyandi**
What would we do without shadows?  I don't know but I added shadow support for it :-)

Submitted PR for FTPopOverMenu PR #25 that adds that feature in the main control https://github.com/liufengting/FTPopOverMenu/pull/25

Also have updated the version number and readme.

image

### CODE REVIEW

**Comment by flyandi** [comment]
Also I changed the defaultProps assignment to use a unified approach.

```Object.keys(Popover.defaultProps).map((id) => {
+      if(props[id] === undefined) props[id] = Popover.defaultProps[id];
+    });```

**Comment by flyandi** [comment]
PR has been merged. You can go ahead and merge this one now.

https://github.com/liufengting/FTPopOverMenu/pull/25

**Comment by prscX** [comment]
Hi @flyandi, I have merged the same. Post testing I will push the release.

Thanks
</ Pranav >

**Comment by flyandi** [comment]
Cool - I just got the FTPopOverMenu 1.3.6 update via pods.

**Comment by prscX** [comment]
Hi @flyandi, I have pushed a release [V0.0.15](https://github.com/prscX/react-native-popover-menu/releases/tag/v0.0.15). Can you please install latest version and validate the same.

Please let me know in case you face any issues. Thanks again for the effort and PR.

Thanks
</ Pranav >

**Pull request merged**
